export type QaMode = "auto" | "joint" | "compare";
export type QaMessageStatus = "pending" | "completed" | "failed" | "cancelled";
export type QaJobStatus = "queued" | "running" | "completed" | "failed" | "cancelled";

export type QaCapabilities = { enabled: boolean };
export type QaDocumentSnapshot = { document_id: string; document_name: string; position: number };
export type QaConversation = {
  conversation_id: string;
  title: string;
  origin: "product" | "legacy_json" | "legacy_gradio";
  rolling_summary: string;
  summary_version: number;
  created_at: string;
  updated_at: string;
  last_message_at: string;
  documents: QaDocumentSnapshot[];
};
export type QaConversationPage = { items: QaConversation[]; next_cursor: string | null };
export type QaSource = {
  citation_id: string;
  document_id: string;
  document_name: string;
  page_number: number | null;
  section: string | null;
  excerpt: string;
  reference: string;
  truncated: boolean;
  source_type: string;
};
export type QaMessage = {
  message_id: string;
  conversation_id: string;
  turn_id: string;
  role: "user" | "assistant";
  status: QaMessageStatus;
  mode: QaMode | "summary" | null;
  content: string;
  source_state: "available" | "none" | "legacy_unavailable";
  retry_of_message_id: string | null;
  safe_error_code: string | null;
  trace_id: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
  sources: QaSource[];
};
export type QaMessagePage = { items: QaMessage[]; next_cursor: string | null };
export type QaJob = {
  job_id: string;
  conversation_id: string;
  input_message_id: string;
  assistant_message_id: string;
  status: QaJobStatus;
  stage: string;
  progress: number;
  cancel_requested_at: string | null;
  attempt_count: number;
  max_attempts: number;
  safe_error_code: string | null;
  trace_id: string | null;
  created_at: string;
  started_at: string | null;
  finished_at: string | null;
  updated_at: string;
};
export type QaDeletion = {
  deletion_id: string;
  target_type: "conversation" | "document";
  target_id: string;
  status: "queued" | "running" | "completed" | "failed";
  stage: string;
  affected_conversation_count: number;
  attempt_count: number;
  safe_error_code: string | null;
  trace_id: string | null;
  created_at: string;
  updated_at: string;
};
