import AxeBuilder from "@axe-core/playwright";
import type { Page } from "@playwright/test";
import { expect, notesTest as test, registerUser, uniqueUsername } from "./fixtures";

async function checkLayout(page: Page) {
  const result = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"]).analyze();
  const severe = result.violations.filter(item => item.impact === "serious" || item.impact === "critical");
  expect(severe, JSON.stringify(severe, null, 2)).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1);
  await page.evaluate(async () => {
    (document.activeElement as HTMLElement | null)?.blur();
    window.scrollTo(0, 0);
    await document.fonts.ready;
    await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
  });
}

test("learning plans persist, complete, undo and follow document deletion", async ({ page, appUrl, appServer }, testInfo) => {
  test.slow();
  const filename = `学习资料-${testInfo.project.name}.md`;
  const title = "可追溯的阅读与复习计划";
  const username = uniqueUsername(`learning_${testInfo.project.name}`);
  await registerUser(page, appUrl, username);
  await page.goto(`${appUrl}/learning`);
  await expect(page.getByText("当前没有任务。", { exact: true })).toBeVisible();
  await checkLayout(page);
  await page.goto(`${appUrl}/documents`);
  await page.locator(".document-toolbar").getByRole("button", { name: "导入文档" }).click();
  await page.getByLabel("选择文档").setInputFiles({ name: filename, mimeType: "text/markdown", buffer: Buffer.from("# 学习计划\n阅读时记录证据，复习时回忆关键概念。") });
  await page.getByRole("button", { name: "开始导入" }).click();
  const row = page.locator("li.document-row").filter({ hasText: filename });
  await expect(row).toBeVisible({ timeout: 30000 });
  await page.goto(`${appUrl}/learning`);
  await page.getByRole("button", { name: "学习计划", exact: true }).click();
  await page.getByLabel("学习文档").selectOption({ label: filename });
  await page.getByLabel("计划名称").fill(title);
  await page.getByLabel("周期（天）").fill("2");
  const createdResponse = page.waitForResponse(response => response.url() === `${appUrl}/api/v1/learning/plans` && response.request().method() === "POST");
  await page.getByRole("button", { name: "创建计划", exact: true }).click();
  const response = await createdResponse;
  expect(response.status()).toBe(201);
  const { plan } = await response.json();
  expect(plan.task_count).toBe(2);
  await expect(page.getByText("计划已创建。", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: `${title} · 任务`, exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "标记完成", exact: true })).toHaveCount(2);
  await checkLayout(page);
  await page.screenshot({ path: testInfo.outputPath("learning-plans.png"), fullPage: true });
  await page.getByRole("button", { name: "今日任务", exact: true }).click();
  await expect(page.getByRole("button", { name: "标记完成", exact: true })).toHaveCount(1);
  await checkLayout(page);
  await page.screenshot({ path: testInfo.outputPath("learning-today.png"), fullPage: true });
  await page.getByRole("button", { name: "标记完成", exact: true }).click();
  await expect(page.getByText("当前没有任务。", { exact: true })).toBeVisible();
  await page.getByLabel("任务范围").selectOption("completed");
  await page.getByRole("button", { name: "恢复未完成", exact: true }).click();
  await expect(page.getByText("当前没有任务。", { exact: true })).toBeVisible();
  await page.getByLabel("任务范围").selectOption("today");
  await expect(page.getByRole("button", { name: "标记完成", exact: true })).toBeVisible();
  await appServer.restart();
  await page.reload();
  await expect(page.getByRole("heading", { name: "登录", exact: true })).toBeVisible();
  await page.getByLabel("用户名").fill(username);
  await page.getByLabel("密码", { exact: true }).fill("e2e-only-passphrase");
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByRole("heading", { name: "学习中心", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "标记完成", exact: true })).toBeVisible();
  const tasksResponse = await page.request.get(`${appUrl}/api/v1/learning/plans/${plan.id}/tasks`);
  expect(tasksResponse.status()).toBe(200);
  const tasks = (await tasksResponse.json()).items;
  expect(tasks).toHaveLength(2);
  expect(tasks[0].completed).toBe(false);
  expect(tasks[0].version).toBe(3);
  await page.goto(`${appUrl}/documents`);
  await row.getByRole("button", { name: `删除 ${filename}` }).click();
  await page.getByRole("dialog", { name: `删除 ${filename}` }).getByRole("button", { name: "确认删除" }).click();
  await expect(row).toHaveCount(0);
  await expect.poll(async () => (await page.request.get(`${appUrl}/api/v1/learning/plans/${plan.id}`)).status()).toBe(404);
  await page.goto(`${appUrl}/learning`);
  await page.getByRole("button", { name: "学习计划", exact: true }).click();
  await expect(page.getByText("还没有学习计划。", { exact: true })).toBeVisible();
});
